# Generated by Django 5.1.3 on 2024-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('instagram', 'Instagram')], max_length=50)),
                ('count', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='sourceSight_date_aba2b2_idx'), models.Index(fields=['source'], name='sourceSight_source_d93563_idx')],
            },
        ),
    ]
